### ISSUE TITLE
Script auto activates, mark all videos as unavailable and writes the channel's name twice, doesn't show actually removed videos

### ISSUE THREAD

**Issue by vdst** [Jopik1/filmot-title-restorer#1]
Hi,

I have been encountering an issue for the last few weeks with the script.

#Expected behavior#

Have an option in the playlist's settings drop down menu to reload the page, showing unavailable videos surrounded by a blue rectangle.

#Current behavior#

(Before enabling the option in the drop-down menu to show unavailable videos)
When loading the playlist's page, (nearly) all videos are marked as removed (shown in blue). I estimate that 98% of the videos in my playlists are affected.
In addition, only those marked as unavailable (when they are) duplicate the uploader's name. I.E.: instead of having "channelname", the script shows "channelnamechannelname".

(After enabling)
Shows only the thumbnail and uploader's name on available videos, no title. Private or deleted videos only have the missing thumbnail, no title, no channel name and no blue highlight to indicate it was removed. The restored counter is obviously also broken.

#Advanced details

I could not find the logic behind why the ones who aren't marked as deleted are shown normally. It's a mix of both old and new videos, both with and without special characters, from various uploaders, they have descriptions and comments like any other videos, ....
All the videos are saved in private playlists, but the same problem happens with private and public playlists and videos.
It happens when both logged in as the playlist's creator and as an unregistered visitor.
As far as I can tell, it also affects newly created playlists and newly added videos in those playlists.

The bug is observable on both Firefox 98.0.2 (32-Bit) using Greasemonkey and also on a freshly installed script on Chrome (Version 100.0.4896.75 (Official Build) (64-bit)) using Tapermonkey.
Os is Windows 10 21h1.

If more information is needed, I will gladly provide what I can.

Thank you for your script and time you have put into this.

Best regards,
vdst

**Comment by Jopik1** [comment]
Thanks for reporting, this was due to youtube format change, it erroneously detected working videos as deleted.
Fixed by detecting the channel name which is missing on deleted videos in the current format.
Previously it used the aria-label which was missing on deleted videos but in current YouTube format they removed the aria-labels from all video links.
Please update to the current version - version 0.35 and let me know if there are any other issues.
