### ISSUE TITLE
Not working in the new youtube layout

### ISSUE THREAD

**Issue by fourteen-1** [Jopik1/filmot-title-restorer#2]
Hi, 

This script no longer works on the new youtube layout. Please fix it.

Thanks.

**Comment by Jopik1** [comment]
Thanks, I am investigating.
Seems that some people get the new layout and some get the old one.
I'd need to make sure the fix works for both.

**Comment by Jopik1** [comment]
corrected in version 0.36

**Comment by Jopik1** [comment]
@fourteen-1 could you please verify it works for you?

**Comment by heywolf15** [comment]
It works on my end

**Comment by fourteen-1** [comment]
> @fourteen-1 could you please verify it works for you?

Yes, it is working now! Thank you so much for fixing it :)
