### ISSUE TITLE
No button

### ISSUE THREAD

**Issue by hugo9655** [Jopik1/filmot-title-restorer#6]
The description says there should be a button in the playlist menu, but theres nothing there. Maybe new YT layout issue?

**Comment by Jopik1** [comment]
It's the YT button labeled "show unavalable videos" for example https://www.youtube.com/playlist?list=PLU1qYmzYerlrMNslZ8C7Q3f9qgPha9Diy see the attached image
<img width="413" alt="Untitled222" src="https://github.com/user-attachments/assets/b087d11a-37ad-40c5-be15-707b25d0c0d3">

**Comment by Jopik1** [comment]
It only restores titles for Ids in the filmot database, the db is not comprehensive. Try the playlist I linked.
